spring:
  application:
    name: bf6-detector

  datasource:
    url: jdbc:postgresql://localhost:5432/bf6_tracker
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        default_schema: bf6_detector_schema

app:
  name: "@project.name@"
  version: "@project.version@"
  java-version: "@java.version@"
