server:
  port: 8080

spring:
  application:
    name: bf6-detector

  datasource:
    url: jdbc:postgresql://localhost:5432/bf6_tracker
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        default_schema: bf6_detector_schema

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: bf6-tracker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

app:
  name: "@project.name@"
  version: "@project.version@"
  java-version: "@java.version@"
